# Travis CI Configuration File

sudo: false

# Tell Travis CI we're using PHP
language: php

cache:
  - composer
  - $HOME/.composer/cache
  - $HOME/.npm

# PHP version used in first build configuration.
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

# WordPress version used in first build configuration.
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.6 WP_MULTISITE=1
    - WP_VERSION=4.5 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=1

install:
  - curl -s http://getcomposer.org/installer | php

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
      fi
  - composer require satooshi/php-coveralls '~1.0'

script:
  - phpcs -p -s -n . --standard=./ruleset.xml --extensions=php
  - jscs -c .jscsrc .
  - jshint .
  - phpunit --coverage-clover=build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls --verbose --exclude-no-stmt
